### ISSUE TITLE
Add additional keywords to the ban list

### ISSUE THREAD

**Issue by formlesstree4** [discord-csharp/CSharpRepl#1]
Add these to the blacklist:
- extern
- Buffer.MemoryCopy
- IntPtr
- [DllImport]
- [DllImportAttribute]

**Comment by willaien** [comment]
SmtpClient should probably go on there, too.

**Comment by Cisien** [comment]
Going the other direction and opening this up to whatever people want to run, since we have the ability to ban people who abuse.
