### ISSUE TITLE
[Feature] Additional Language Support.

### ISSUE THREAD

**Issue by TheBrambleShark** [discord-csharp/CSharpRepl#18]
I will be submitting a PR for this as I develop code. However, I will be primarily focusing development on the back-end ([CSDiscord](https://github.com/discord-csharp/CSDiscord)) first, then I will swing around and add capability to the bot. If any of you can think of any other languages or features you would want support for, let me know in the discussion below. If there's strong enough support for it, I'll be sure to add it to the list.

Planned languages:
[ ] F#
[ ] VB

Proposed languages:
[ ] C++ (using C++/WinRT)

Other (optional) features:
[ ] Efficient data offloading (especially for compiling C++ and other languages not specifically supported by Roslyn)
[ ] Some sort of plugin system to add additional languages on the fly (NetStandard library - query function to find the name of the language it supports and methods to build and execute said code)

**Comment by Cisien** [comment]
Closing until a PR shows up
