### ISSUE TITLE
Block a potentially dangerous library: NativeLibrary

### ISSUE THREAD

**Issue by sos-dll** [discord-csharp/CSharpRepl#41]
[`NativeLibrary`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary) could be abused. For example:
It is possible to obtain a function pointer to the `libc`'s `reboot` function (since REPL is run on Linux), someone could shutdown the machine executing the REPL code (one-node at a time, since the code would need to be executed on each node?).
```cs
if (NativeLibrary.TryLoad("libc-2.28.so", out var libc)) {
  if (NativeLibrary.TryGetExport(libc, "reboot", out var reboot)) {
    Console.WriteLine("libc.so!reboot @ 0x{0:X16}", reboot.ToInt64());
    /* ~ redacted actual reboot code, for security reasons ~ */
  }
}
```
Just something to keep an eye on.

**Comment by Cisien** [comment]
Thanks for the concern, but I have no plans to restrict this (or other) APIs at this time. There are legitimate uses for this API for the primary purpose of the bot -- demonstration. I'm confident that the current mitigations in place are sufficient to protected against abuse of this API, and that any abuse can be detected by the moderation staff and dealt with.
